[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = true
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]

fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fmt]
line_length = 100
